log_level: DEBUG

feature_flags:
  all: true

inference:
  address: "http://localhost:2114/api/v1/infer"
  timeout: 10
  token: "98eb568c-dea5-4347-a3a5-583478983bb9"
  bm25:
    # Hyperparameters for bm25
    k: 1.2
    b: 0.75
    avg_len: 256.0
    # Tokenizer to use. Can be one of prefix, whitespace, word, multilingual. Default is word.
    tokenizer: word
    # Configurations of the tokenizer
    tokenizer_config:
      # Whether to convert all tokens to lowercase.
      lowercase: false
      # Use predefined set of stopwords for english.
      stopwords_filter: english
      # Add custom words to the stopword filter.
      custom_stopwords:
        - hello
      # Enable stemming with the english ruleset and snowball as stemming algoritm.
      stemmer:
        type: snowball
        language: english
      # Specify min and max token length used in some tokenizers.
      min_token_len: null
      max_token_len: null

service:
  host: 127.0.0.1
  http_port: 6333
  # Uncomment to enable gRPC:
  #grpc_port: 6334
  #api_key: your_secret_api_key_here

cluster:
  resharding_enabled: true

storage:
  performance:
    # Number of parallel threads used for search operations. If 0 - auto selection.
    max_search_threads: 4

  optimizers:
    # Minimum interval between forced flushes.
    flush_interval_sec: 5

    # Do not create too much segments in dev
    default_segment_number: 2

  handle_collection_load_errors: true
