name: Hammering

on:
  push:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Install minimal stable
      uses: dtolnay/rust-toolchain@1.77.0
    - uses: actions/checkout@v4
      with:
        fetch-depth: 300
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy hammering
      shell: bash
      run: cp -a ./tools/hammering2.sh ./hammering.sh

    - name: Run on a good revision
      shell: bash
      run: |
        git checkout 50c7a7e~200
        bash ./hammering.sh # should pass

    - name: Run on a bad revision
      shell: bash
      run: |
        git checkout 50c7a7e
        rc=0; bash ./hammering.sh || rc=$?; [ $rc = 1 ] # should fail

    - name: Run bisect
      shell: bash
      run: |
        git bisect start 50c7a7e 50c7a7e~200
        git bisect run bash ./hammering.sh
