name: Integration tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-consensus:

    runs-on: ubuntu-latest

    steps:
      - name: Install minimal stable
        uses: dtolnay/rust-toolchain@stable
      - uses: actions/checkout@v4
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
      - name: Install dependencies
        run: sudo apt-get install clang
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install pytest
        run: pip install pytest requests
      - name: Build
        run: cargo build --features service_debug
      - name: Run integration tests - multiple peers - pytest
        run: |
          
          for i in {1..20}
          do
            pytest tests/consensus_tests/test_collection_recovery_limits.py::test_collection_recovery_below_limit -s
          done
          
        timeout-minutes: 60
      - name: upload logs in case of failure
        uses: actions/upload-artifact@v4
        if: failure() || cancelled()
        with:
          name: consensus-test-logs
          retention-days: 90 # default max value
          path: consensus_test_logs
