name: Rust tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019 ]

    steps:
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    - name: Install minimal stable
      uses: dtolnay/rust-toolchain@stable
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
#    - name: Setup tmate session
#      uses: mxschmitt/action-tmate@v3
    - name: Run tests
      run: cd lib/segment && cargo test --test integration test_create_segment
